name: Bump Version

run-name: Bump version - requested by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump Type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  call-shared-version-bump-workflow:
    uses: plantemoran-appdev/shared-github-workflows/.github/workflows/shared--bump-version--node.yml@develop
    with:
      bumpType: ${{ inputs.bumpType }}
