name: Copilot Environment Setup

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  pull_request:
    branches:
      - develop
    paths:
      - .github/workflows/copilot-setup-steps.yml

  workflow_dispatch:

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    name: Copilot Setup Steps
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for the steps below.
    # Copilot will be given its own token for its operations.
    permissions:
      contents: read

    env:
      NODE_VERSION: 22.x # ----- the version of node.js to use

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # -- fetch full repository history (not shallow clone)

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup .npmrc
        run: |
          echo "@awesome.me:registry=https://npm.fontawesome.com/"                           >> .npmrc
          echo "@fortawesome:registry=https://npm.fontawesome.com/"                          >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONT_AWESOME_PKG_MGR_TOKEN }}" >> .npmrc

      - name: Install npm Dependencies
        run: npm ci
